<?php
/**
* Implements hook_menu().
*/
function dss_betamessage_menu() {
  $items = array();
  $items['admin/config/user-interface/dss-betamessage'] = array(
    'title' => 'DSS Beta Message',
    'description' => 'Configuration for the DSS Beta Message module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dss_betamessage_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
* Form builder
*/
function dss_betamessage_form($form, &$form_state) {
  $dss_betamessage_settings = variable_get('dss_betamessage_settings');

  $form['messagewords'] = array(
    '#type' => 'textarea',
    '#title' => t('Beta message words'),
    '#default_value' => t($dss_betamessage_settings['messagewords']),
    '#rows' => 4,
    '#cols' => 60,
  );

  $form['wrapper_element'] = array(
    '#type' => 'textfield',
    '#title' => t('Selector for element to attach beta tag to'),
    '#default_value' => t($dss_betamessage_settings['wrapper_element'])
  );

  $form['wrapper_bg'] = array(
    '#type' => 'textfield',
    '#title' => t('HEX code for the background of the banner (include #)'),
    '#default_value' => t($dss_betamessage_settings['wrapper_bg'])
  );

  $form['wrapper_text_color'] = array(
    '#type' => 'checkbox',
    '#title' => t('Toggle colour of text'),
    '#default_value' => $dss_betamessage_settings['wrapper_text_color'],
    '#return_value' => "black-text",
    '#description' => t('Enable to change the colour of the text to black'),
  );

  $form['wrapper_hide_beta'] = array(
    '#type' => 'checkbox',
    '#title' => t('Hide beta tag'),
    '#default_value' => $dss_betamessage_settings['wrapper_hide_beta'],
    '#return_value' => "hide-beta",
  );


  // Submit button
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings')
  );
  return $form;
}

/**
* Save configuration settings
*/
function dss_betamessage_form_submit($form, &$form_state) {
  $dss_betamessage_settings = array(
    'messagewords' => $form_state['values']['messagewords'],
    'wrapper_element' => $form_state['values']['wrapper_element'],
    'wrapper_bg' => $form_state['values']['wrapper_bg'],
    'wrapper_text_color' => $form_state['values']['wrapper_text_color'],
    'wrapper_hide_beta' => $form_state['values']['wrapper_hide_beta'],
  );
  variable_set('dss_betamessage_settings',$dss_betamessage_settings);
  drupal_set_message(t('The settings have been saved'));
}

/**
 * Implements hook_page_build().
 */
function dss_betamessage_page_build(&$page) {
  $dss_betamessage_settings = variable_get('dss_betamessage_settings');

  $page['page_top']['betamessage'] = array(
    '#weight' => 25,
    '#markup' => '<p class="betamessage '. $dss_betamessage_settings["wrapper_text_color"].' '. $dss_betamessage_settings["wrapper_hide_beta"].'" data-attach-to="' . $dss_betamessage_settings["wrapper_element"] . '" style="background: '. $dss_betamessage_settings["wrapper_bg"] .' ;"><span class="betamessage-text"><span class="betamessage-tag">Beta</span> &nbsp;' . $dss_betamessage_settings['messagewords'] . '</span><span class="betamessage-close"><a href="#" aria-label="Hide this beta message">Hide this</a></span></p>',
  );

  drupal_add_css(drupal_get_path('module', 'dss_betamessage') . '/betamessage.css', array('group' => CSS_THEME, 'type' => 'file', 'preprocess' => TRUE));
  drupal_add_js(drupal_get_path('module', 'dss_betamessage') . '/betamessage.js', array('group' => JS_DEFAULT, 'type' => 'file', 'scope'=>'footer', 'preprocess' => TRUE));
}

/**
 * Implements hook_preprocess_html().
 */
function dss_betamessage_preprocess_html(&$vars) {
  $vars['classes_array'][] = 'is-beta';
}
